# Atividade 1
numero_int = float(input("digite um numero para saber o quadrado dele: "))
quadrado = (numero_int ** 2)
print(quadrado)

# Atividade 2
nome = input("digite seu nome")
sobrenome = input("digite seu sobrenome")

print("seja bem vindo ", nome, sobrenome)

# Atividade 3
n1 = (input("digite um numero inteiro:")) 
n2 = (input(" digite um outro numero inteiro"))
print(n1, n2)

# ATIVIDADE 4
palavra = "python"
numero = int(input("digite um numero"))
print (palavra,numero)

# ATIVIDADE 5
FRASE = "HOJE EU VOU PARA O (A)"
local = (input("digite um local:"))
print(FRASE,local)